pollster/config/routes.rb
Pollster::Application.routes.draw do

  root :to => 'polls#index'

  resources :polls do
    resources :questions do
      resources :responses
    end
  end

  resources :questions, :only => [] do
    resources :responses
  end

end

pollster/app/models/poll.rb
class Poll < ActiveRecord::Base
  attr_accessible :edit_url, :name

  has_many :questions, :dependent => :destroy

  before_create :generate_edit_url


  private

  def generate_edit_url
    self.edit_url = SecureRandom.hex
  end

end

pollster/app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :body, :poll_id

  belongs_to :poll
  has_many :responses, :dependent => :destroy

end

pollster/app/models/response.rb
class Response < ActiveRecord::Base
  attr_accessible :body, :question_id

  belongs_to :question
end

pollster/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

pollster/app/controllers/polls_controller.rb
class PollsController < ApplicationController
  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @polls }
    end
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
    @poll = Poll.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @poll }
    end
  end

  # GET /polls/new
  # GET /polls/new.json
  def new
    @poll = Poll.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @poll }
    end
  end

  # GET /polls/1/edit
  def edit
    @poll = Poll.find_by_edit_url(params[:id])
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(params[:poll])

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render json: @poll, status: :created, location: @poll }
      else
        format.html { render action: "new" }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /polls/1
  # PUT /polls/1.json
  def update
    @poll = Poll.find(params[:id])

    respond_to do |format|
      if @poll.update_attributes(params[:poll])
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll = Poll.find(params[:id])
    @poll.destroy

    respond_to do |format|
      format.html { redirect_to polls_url }
      format.json { head :no_content }
    end
  end
end

pollster/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :load_poll

  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: poll_question_path(@question.poll, @question) }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: poll_question_path(@question.poll, @question) }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])
    @question.poll = @poll
    respond_to do |format|
      if @question.save
        format.html { redirect_to poll_question_path(@question.poll, @question), notice: 'Question was successfully created.' }
        format.json { render json: poll_question_path(@question.poll, @question), status: :created, location: poll_question_path(@question.poll, @question) }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to poll_question_path(@question.poll, @question), notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to poll_questions_path(@poll) }
      format.json { head :no_content }
    end
  end

  private

  def load_poll
    @poll = Poll.find params[:poll_id]
  end
end

pollster/app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
 before_filter :load_poll, :load_question
  def index
    @responses = Response.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: poll_question_response_path(@poll, @question) }
    end
  end

  # GET /responses/1
  # GET /responses/1.json
  def show
    @response = Response.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: poll_question_response_path(@poll, @question) }
    end
  end

  # GET /responses/new
  # GET /responses/new.json
  def new
    @response = Response.new
    @question_id = params[:question_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: poll_question_response_path(@poll, @question) }
    end
  end

  # GET /responses/1/edit
  def edit
    @response = Response.find(params[:id])
  end

  # POST /responses
  # POST /responses.json
  def create
    @response = Response.new(params[:response])
    @response.question = @question

    respond_to do |format|
      if @response.save
        format.html { redirect_to poll_question_response_path(@poll, @question, @response), notice: 'Response was successfully created.' }
        format.json { render json: poll_question_response_path(@poll, @question, @response), status: :created, location: @response }
      else
        format.html { render action: "new" }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /responses/1
  # PUT /responses/1.json
  def update
    @response = Response.find(params[:id])

    respond_to do |format|
      if @response.update_attributes(params[:response])
        format.html { redirect_to poll_question_response_path(@poll, @question), notice: 'Response was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.json
  def destroy
    @response = Response.find(params[:id])
    @response.destroy

    respond_to do |format|
      format.html { redirect_to poll_question_responses_path(@poll, @question) }
      format.json { head :no_content }
    end
  end

  private

  def load_poll
    @poll = Poll.find params[:poll_id]
  end

  def load_question
    @question = Question.find params[:question_id]
  end

end

pollster/app/helpers/application_helper.rb
module ApplicationHelper
end

pollster/app/helpers/polls_helper.rb
module PollsHelper
end

pollster/app/helpers/questions_helper.rb
module QuestionsHelper
end

pollster/app/helpers/responses_helper.rb
module ResponsesHelper
end

pollster/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pollster</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

pollster/app/views/layouts/fixed.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Pollster" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Pollster</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
             <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

pollster/app/views/polls/_form.html.erb
<%= form_for @poll, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :edit_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :edit_url, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                polls_path, :class => 'btn' %>
  </div>
<% end %>

pollster/app/views/polls/edit.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

pollster/app/views/polls/index.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:edit_url) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= link_to poll.id, poll_path(poll) %></td>
        <td><%= poll.name %></td>
        <td><%= poll.edit_url %></td>
        <td><%=l poll.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_poll_path(poll), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      poll_path(poll),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_poll_path,
            :class => 'btn btn-primary' %>

pollster/app/views/polls/new.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

pollster/app/views/polls/show.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @poll.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:edit_url) %>:</strong></dt>
  <dd><%= link_to edit_poll_url(@poll.edit_url), edit_poll_url(@poll.edit_url) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:public_url) %>:</strong></dt>
  <dd><%= link_to poll_url, poll_url %></dd>

</dl>
<dt><strong><%= model_class.human_attribute_name(:Questions) %>:</strong></dt>
  <% @poll.questions.each do |question| %>
    <tr>
      <td><%= link_to question.id, poll_question_path(@poll, question) %></td>
      <td><%= question.body %></td>
      <td><%=l question.created_at %></td>
      <td>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_poll_question_path(@poll, question), :class => 'btn btn-mini' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    poll_question_path(@poll, question),
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-mini btn-danger' %>
      </td>
    </tr>
  <% end %>




<div class="form-actions">
  <%= link_to t('.add question'),
              new_poll_question_path(@poll),
              :class => 'btn'  %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
              polls_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_poll_path(@poll), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              poll_path(@poll),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

pollster/app/views/questions/_form.html.erb
<%= form_for [@poll, @question], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :body, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :body, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                poll_path(@poll), :class => 'btn' %>
  </div>
<% end %>

pollster/app/views/questions/edit.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

pollster/app/views/questions/index.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:body) %></th>
      <th><%= model_class.human_attribute_name(:poll_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= link_to question.id, question_path(question) %></td>
        <td><%= question.body %></td>
        <td><%= question.poll_id %></td>
        <td><%=l question.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_question_path(question), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      question_path(question),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_question_path,
            :class => 'btn btn-primary' %>

pollster/app/views/questions/new.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

pollster/app/views/questions/show.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @question.body %></dd>
  <dt><strong><%= model_class.human_attribute_name(:poll_id) %>:</strong></dt>
  <dd><%= @question.poll_id %></dd>
</dl>

<dt><strong><%= model_class.human_attribute_name(:Responses) %>:</strong></dt>
  <% @question.responses.each do |response| %>
    <tr>
      <td><%= link_to response.id, poll_question_response_path(@poll, @question, response) %></td>
      <td><%= response.body %></td>
      <td><%=l response.created_at %></td>
      <td>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_poll_question_response_path(@poll, @question, response), :class => 'btn btn-mini' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    poll_question_response_path(@poll, @question, response),
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-mini btn-danger' %>
      </td>
    </tr>
  <% end %>

<div class="form-actions">
  <%= link_to t('.respond'),
              new_poll_question_response_path(@poll,@question),
              :class => 'btn'  %>

  <%= link_to t('.back', :default => t("helpers.links.back")),
              poll_questions_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_poll_question_path(@question.poll_id, @question), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              poll_question_path(@question.poll_id, @question),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

pollster/app/views/responses/_form.html.erb
<%= form_for [@poll, @question, @response ], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :body, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :body, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :question_id, :class => 'control-label' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                poll_question_responses_path(@poll, @question), :class => 'btn' %>
  </div>
<% end %>

pollster/app/views/responses/edit.html.erb
<%- model_class = Response -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

pollster/app/views/responses/index.html.erb
<%- model_class = Response -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:body) %></th>
      <th><%= model_class.human_attribute_name(:question_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @responses.each do |response| %>
      <tr>
        <td><%= link_to response.id, poll_question_response_path(@poll, @question, response)%></td>
        <td><%= response.body %></td>
        <td><%= response.question_id %></td>
        <td><%=l response.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_poll_question_response_path(@poll, @question, response), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      poll_question_response_path(@poll, @question, response),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_poll_question_response_path(@poll, @question),
            :class => 'btn btn-primary' %>

pollster/app/views/responses/new.html.erb
<%- model_class = Response -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

pollster/app/views/responses/show.html.erb
<%- model_class = Response -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @response.body %></dd>
  <dt><strong><%= model_class.human_attribute_name(:question_id) %>:</strong></dt>
  <dd><%= @response.question_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              poll_question_responses_path(@poll, @question), :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_poll_question_response_path(@poll, @question, @response), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              poll_question_response_path(@poll, @question, @response),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>